language: python
scripts: echo Working
deploy:
  provider: pypi
  username: __token__
  password:
    secure: pLo8LQWbAJaP8xjDsUmjE8/VIrgimjD6Ioo3TntwGW4M+056vOQPgAOMuomTe3xtVHRyBO7ZYxwvOqEedZkpF9VbJGoNCrcbmJmeeR+2JhwCoc2d9YUWb2tkIdsMBlgkfc1Fbf3Afr+3PhBa2vEruNknChbhkTWkdoSVnU/6K7i5NwbrUEszWBuag+ilsF9FW6+a5UUPLGfCoXymezXnNc7jXj9NvS5P5zMdQQJiMm/ePnjwzcNRJE8EH1Ya3dl/UdflXxakP6/WtNqRMRhyPyeROOUf3MIHfBCksqGHOt4CVJzItJkFXX08TzdaZ/dY0gZufg50EiV0IC1cjMBo5/Jinor7wpndHelet3tdcv2vEzXEvjfr/mQlZ3S09y0ZoUBwvh0r2gbSKGaSDKv9wi4IvUZjA09FXCJPLuIj06fiMtfiFvO4AwvwV9wRhd6SIk1YHDFLVUDMLLJuiN4KBWDWqk2L6NMb3l80g3EyQ6Cs6bvCR3r9f4/GXCWoTp9ltlzQsYPBfNKg+kJVgRl9sx0If8WrUC5iOJPYgpcdxhLJyYPw10D44DhhFQxxW3pkxhcSySmACPHomkuBWsDKkY04EmcH76JzzOpQkpZych0Wep4RV4mQkiPxI/YVwermJpQY1w5WUfuVRv+JgBl9WiuBWVvmGk2IqRIevBo9zwk=
  on:
    tags: true
